# [tools]
# node = '24'
# python = '3.12'
[env]
# LEGO_CONFIG = "cert/.lego.yml"
[tasks.dev]
run = 'npm run dev'
[tasks.test]
run = 'pytest'
[tasks]
hello = "seq 0 142"
cloudflared = "cargo run --example cloudflared"
lego = "cd cert; lego"
database = "cd database;docker compose up -d"
database_clean = "cd database;docker compose down --remove-orphans"
