storage: .lego
userAgent: lego-cli/v5.3.1
accounts:
  noemail@example.com:
    server: https://acme-v02.api.letsencrypt.org/directory
    keyType: EC256
challenges:
  cf:
    dns:
      provider: cloudflare
certificates:
  rsa_4096:
    domains:
      - '*.dt-fwb.ipv64.de'
    keyType: EC256
    challenge: cf
    account: noemail@example.com
    renew:
      ari: {}
