tunnel: urmom
credentials-file: ./cert/.cloudflared/3c28cce9-82a6-4659-bdd7-8d0e5dc2d469.json
ingress:
  # - hostname: 30.imsimp.ipv64.de
  - hostname: www.dt-fwb.ipv64.de
    service: http://localhost:3100
  - service: http_status:404
