tunnel: urmom
credentials-file: ./cert/.cloudflared/fd0b41d9-88bb-4b1b-a937-9927ea2dd596.json
ingress:
  - hostname: www.dt-fwb.ipv64.de
    service: http://localhost:3100
    # originRequest:
    #   originServerName: www.dt-fwb.ipv64.de
  - service: http_status:404
